# Generated by Django 5.0.6 on 2024-07-30 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discipline_code', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('discipline_date', models.DateField()),
                ('discipline_heure', models.TimeField()),
                ('discipline_motif', models.TextField(blank=True, null=True)),
                ('discipline_date_demande', models.DateTimeField(blank=True, null=True)),
                ('discipline_date_retour', models.DateTimeField(blank=True, null=True)),
                ('discipline_type', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organisation_code', models.CharField(max_length=50, unique=True)),
                ('organisation_name', models.CharField(max_length=50, unique=True)),
                ('organisation_description', models.TextField(blank=True, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='account.organisation')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_code', models.CharField(max_length=30, unique=True)),
                ('job_title', models.CharField(max_length=30)),
                ('job_description', models.TextField(blank=True, null=True)),
                ('job_salary', models.FloatField(blank=True, null=True)),
                ('organisation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='account.organisation')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cni_number', models.CharField(max_length=30, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('sexe', models.CharField(max_length=30)),
                ('birthday', models.DateField()),
                ('birthplace', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=15)),
                ('matricule', models.CharField(blank=True, max_length=30)),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='persons', to='account.job')),
            ],
        ),
        migrations.CreateModel(
            name='Localisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('localisation_code', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('localisation_lat', models.FloatField(blank=True, default=0.0, null=True)),
                ('localisation_long', models.FloatField(blank=True, default=0.0, null=True)),
                ('discipline', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='localisations', to='account.discipline')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='localisations', to='account.person')),
            ],
        ),
        migrations.CreateModel(
            name='Fonds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fond_code', models.CharField(max_length=30, unique=True)),
                ('fond_name', models.CharField(max_length=30)),
                ('fond_description', models.CharField(max_length=30)),
                ('started_at', models.DateTimeField(blank=True, max_length=15)),
                ('ended_at', models.DateTimeField(blank=True, max_length=30)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='account.fonds')),
                ('autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='author', to='account.person')),
            ],
        ),
        migrations.CreateModel(
            name='Dossiers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dossier_code', models.CharField(max_length=30, unique=True)),
                ('dossier_label', models.CharField(max_length=30)),
                ('dossier_description', models.CharField(blank=True, max_length=30, null=True)),
                ('started_at', models.DateTimeField(max_length=15)),
                ('ended_at', models.DateTimeField(blank=True, max_length=30, null=True)),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personnes', to='account.person')),
            ],
        ),
        migrations.AddField(
            model_name='discipline',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='disciplines', to='account.person'),
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=100)),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='account.person')),
            ],
        ),
        migrations.CreateModel(
            name='Pieces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('piece_code', models.CharField(max_length=30, unique=True)),
                ('piece_title', models.CharField(max_length=30)),
                ('piece_decription', models.CharField(max_length=30)),
                ('file', models.FileField(upload_to='pieces')),
                ('started_at', models.DateTimeField(blank=True, max_length=15)),
                ('ended_at', models.DateTimeField(blank=True, max_length=30)),
                ('dossier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pieces', to='account.dossiers')),
            ],
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serie_code', models.CharField(max_length=30, unique=True)),
                ('serie_name', models.CharField(max_length=30)),
                ('serie_description', models.CharField(max_length=30)),
                ('started_at', models.DateTimeField(blank=True, max_length=15)),
                ('ended_at', models.DateTimeField(blank=True, max_length=30)),
                ('fond', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='series', to='account.fonds')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='account.series')),
            ],
        ),
        migrations.AddField(
            model_name='dossiers',
            name='serie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personnes', to='account.series'),
        ),
    ]
